### PR TITLE
GitHub Actions: PR Validate workflow

### PR DESCRIPTION
**Pull request by cynicaljoy**
Adding a workflow to run the test suite during PRs

Failing tests are expected as that's the current state even if I run locally. I want to get the workflow merged so we can fix the tests in separate PRs.

### CODE REVIEW

**Comment by cynicaljoy** [comment]
failing tests are expected as that's the current state even if I run locally. I want to get the workflow merged so we can fix the tests in separate PRs.

**Comment by cynicaljoy** [comment]
@cleve-fauna I'd like to get this merged so we can use this to validate we're fixing tests

**Comment by cleve-fauna** [comment]
@cynicaljoy how about we merge after the tests start passing : )

I suspect you'll need to rebase once your other PR is merged.

**Comment by cynicaljoy** [comment]
> @cynicaljoy how about we merge after the tests start passing : )
> 
> I suspect you'll need to rebase once your other PR is merged.

having this workflow as part of those PRs will help actually validate they're passing

**Comment by cleve-fauna** [comment]
> > @cynicaljoy how about we merge after the tests start passing : )
> > I suspect you'll need to rebase once your other PR is merged.
> 
> having this workflow as part of those PRs will help actually validate they're passing

I get that. We're just arguing for doing them in a different order. Sorry for wasting time on that.

I just rebased from #41. Let's see how it goes and fix anything that's still failing and then merge this in once we're all green for a clean slate.

Once its merged I'm going to setup a branch protection rule that we can only merge when these are all green.

**Comment by cynicaljoy** [comment]
> > @cynicaljoy how about we merge after the tests start passing : )
> > I suspect you'll need to rebase once your other PR is merged.
> 
> having this workflow as part of those PRs will help actually validate they're passing

and I wasn't going to fix the QueryCheckError tests as part of this PR

**Review by cleve-fauna — APPROVED** [review]
Getting out of darren's way :D

**Pull request merged**
